### ISSUE TITLE
TReturnToElementList Failed...

### ISSUE THREAD

**Issue by ericksonl** [nay7/Elemental#2]
Multiple errors to be reported:
1. Return the the Element List button in air.html gives a "Your file couldn't be accessed" error
2. Return the the Element List button in earth.html returns user to home screen, not element list

**Comment by nay7** [comment]
Error of returning to the elemental list from air.html, was due to list.html being misspelled. This issue has been fixed and should now allow the user to return to the elements list. 

Error of returning to the elemental list from earth.html, was due to the file using the index.html file instead of list.html file. This issue has been fixed and should now allow the user to return to the elements list.

**Comment by oppenheip** [comment]
A good bug report should contain only one bug.
